CREATE TABLE IF NOT EXISTS genre(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS artist(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS album(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	yearOf INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS track(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	timeOf INTEGER NOT NULL,
	albumID INTEGER REFERENCES album(id)
);
CREATE TABLE IF NOT EXISTS collection(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	yearOf INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS genre_artist (
	genreID INTEGER REFERENCES genre(id),
	artistID INTEGER REFERENCES artist(id),
	CONSTRAINT ga_pk PRIMARY KEY(genreID, artistID)
);
CREATE TABLE IF NOT EXISTS artist_album (
	artistID INTEGER REFERENCES artist(id),
	albumID INTEGER REFERENCES album(id),
	CONSTRAINT aa_pk PRIMARY KEY(artistID, albumID)
);
CREATE TABLE IF NOT EXISTS collection_track (
	collectionID INTEGER REFERENCES collection(id),
	trackID INTEGER REFERENCES track(id),
	CONSTRAINT ct_pk PRIMARY KEY(collectionID, trackID)
);