CREATE TABLE IF NOT EXISTS part(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee (
	id SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	partID INTEGER REFERENCES part(id),
	bossID INTEGER NOT NULL
);

ALTER TABLE Employee
ADD FOREIGN KEY (BossID) REFERENCES Employee(id); 

